#!/bin/sh

function backup(){
#pass the backup path as the first arg
#pass the path for the config file as the second arg
	P=$1;
	CONFIG=$2;
	if [ ! -e $P ]; then mkdir $P; fi
	if [ ! -f $CONFIG ]; then echo "no config file"; exit 2; fi
	while read LINE
	do
		if [[ $LINE != \#* ]] && [ "$LINE" ] 
		then
			if [[ $LINE == \?* ]]
			then
				COMMAND=${LINE#?}; #strip the ?
				COMMAND=${COMMAND%%\|*}; #strip the name
				NAME=${LINE##*\|}; #get the name to save as
				`$COMMAND > $P/$NAME`; #run the command and write output
			else
				ORIG=`eval "echo ${LINE%%\|*}"`; #expand the tilde to $HOME
				echo $ORIG;
				NEW="${LINE##*\|}";
				if [ -e "$ORIG" ]
				then
					[[ -d $ORIG ]] && OPTIONS="-r" || OPTIONS="";
					cp $OPTIONS $ORIG "$P/$NEW";
				fi
			fi
		fi
	done < $CONFIG
	cp $CONFIG "$P/config";
}

FPATH=$(dirname $0);
C=0;
while ( true )
do
	if [ ! -e "$FPATH/backups/$C" ];
	then
		break;
	fi
	C=$((C+1));
done

backup "$FPATH/backups/$C" "$FPATH/config";

#symlink the new latest backup
if [ -e "$FPATH/latest" ]
then
	rm "$FPATH/latest";
fi

ln -s "$FPATH/backups/$C" "$FPATH/latest"
