set nocompatible
filetype off

filetype plugin on
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'Shougo/neocomplcache'
Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdtree'

" Keybinding for nerdtree
nmap , :NERDTree<CR>

let g:neocomplcache_enable_at_startup = 1

filetype plugin indent on

set backspace=indent,eol,start

if has('mouse')
  set mouse=a
endif

set autoindent

syntax on
set background=dark
colorscheme solarized

set number

" Custom key mappings
" Map tab to switch tabs
nmap <Tab> gt
nmap <S-Tab> gT
" Map ` to switch between split windows
nmap ` <C-w>w
" Map \ and | to switch windows around vertically and horizontally
nmap \ <C-w>

nmap <silent> <C-Up> :wincmd k<CR>
nmap <silent> <C-Down> :wincmd j<CR>
nmap <silent> <C-Left> :wincmd h<CR>
nmap <silent> <C-Right> :wincmd l<CR>

set tabstop=4
set cindent

set shiftwidth=4
"set so=999
